"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { useLanguage } from "../../../components/language-provider";
import { supabase } from "../../../lib/supabase";

export default function SellProductPage(){
  const {t}=useLanguage();const [userId,setUserId]=useState("");const [fee,setFee]=useState<any>({listing_fee_amount:0,listing_fee_currency:"USD"});const [methods,setMethods]=useState<any[]>([]);
  const [form,setForm]=useState<any>({title:"",description:"",category:"",product_type:"digital",price:"",currency:"USD",image_url:"",delivery_instructions:""});const [method,setMethod]=useState<any>({method_type:"payoneer",label:"Payoneer",account_value:"",instructions:""});const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
  async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/connexion";return}setUserId(user.id);const [{data:s},{data:m}]=await Promise.all([supabase.from("marketplace_settings").select("*").eq("id",1).single(),supabase.from("marketplace_seller_methods").select("*").eq("seller_id",user.id).order("created_at")]);if(s)setFee(s);setMethods(m||[])}
  useEffect(()=>{load()},[]);
  async function upload(file?:File){if(!file||!userId)return;setBusy(true);const ext=file.name.split(".").pop()||"jpg";const path=`${userId}/${Date.now()}.${ext}`;const {error}=await supabase.storage.from("marketplace-products").upload(path,file,{contentType:file.type});if(error){setNotice(error.message);setBusy(false);return}const {data}=supabase.storage.from("marketplace-products").getPublicUrl(path);setForm({...form,image_url:data.publicUrl});setBusy(false)}
  async function addMethod(e:FormEvent){e.preventDefault();const {error}=await supabase.from("marketplace_seller_methods").insert({...method,seller_id:userId});if(error){setNotice(error.message);return}setMethod({method_type:"payoneer",label:"Payoneer",account_value:"",instructions:""});await load()}
  async function create(e:FormEvent){e.preventDefault();setBusy(true);setNotice("");const slug=(form.title.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")+"-"+Date.now().toString().slice(-5));const {data:p,error}=await supabase.from("marketplace_products").insert({...form,slug,seller_id:userId,price:Number(form.price),status:"pending_fee",listing_fee_status:"pending"}).select("id").single();if(error){setNotice(error.message);setBusy(false);return}const {error:o}=await supabase.from("marketplace_listing_fee_orders").insert({product_id:p.id,seller_id:userId,amount:Number(fee.listing_fee_amount||0),currency:fee.listing_fee_currency||"USD",status:Number(fee.listing_fee_amount||0)>0?"pending":"waived"});setBusy(false);setNotice(o?o.message:t({fr:"Produit créé. Il sera publié après validation des frais de publication Vydys.",ar:"تم إنشاء المنتج وسيُنشر بعد اعتماد رسوم Vydys.",en:"Product created. It will be published after the Vydys listing fee is validated."}))}
  return <section className="section page-top sell-product-page"><div className="container"><div className="page-hero"><span className="eyebrow">Vydys Marketplace</span><h1>{t({fr:"Vendez sur Vydys.",ar:"بع على Vydys.",en:"Sell on Vydys."})}</h1><p>{t({fr:"Vous recevez 100% du paiement de l’acheteur directement. Vydys facture seulement les frais de publication.",ar:"تحصل مباشرة على كامل دفعة المشتري. تفرض Vydys رسوم النشر فقط.",en:"You receive the buyer payment directly. Vydys only charges the listing fee."})}</p></div>
  <div className="sell-product-layout"><main><form className="panel settings-form" onSubmit={create}><div className="listing-fee-banner"><span>{t({fr:"Frais de publication",ar:"رسوم النشر",en:"Listing fee"})}</span><strong>{Number(fee.listing_fee_amount||0)} {fee.listing_fee_currency}</strong><small>{t({fr:"Une fois par produit. Aucune commission Vydys sur vos ventes.",ar:"مرة واحدة لكل منتج. لا عمولة على المبيعات.",en:"One-time per product. No Vydys sales commission."})}</small></div><div className="settings-grid"><label className="wide"><span>{t({fr:"Nom du produit",ar:"اسم المنتج",en:"Product name"})}</span><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="wide"><span>{t({fr:"Description",ar:"الوصف",en:"Description"})}</span><textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label><span>{t({fr:"Catégorie",ar:"الفئة",en:"Category"})}</span><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label><span>{t({fr:"Type",ar:"النوع",en:"Type"})}</span><select value={form.product_type} onChange={e=>setForm({...form,product_type:e.target.value})}><option value="digital">Digital</option><option value="service">Service</option><option value="physical">Physical</option></select></label><label><span>{t({fr:"Prix",ar:"السعر",en:"Price"})}</span><input required type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label><span>{t({fr:"Devise",ar:"العملة",en:"Currency"})}</span><input value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></label><label className="wide"><span>{t({fr:"Image",ar:"الصورة",en:"Image"})}</span><input type="file" accept="image/*" onChange={e=>upload(e.target.files?.[0])}/></label><label className="wide"><span>{t({fr:"Livraison / accès après achat",ar:"التسليم / الوصول بعد الشراء",en:"Delivery / access after purchase"})}</span><textarea value={form.delivery_instructions} onChange={e=>setForm({...form,delivery_instructions:e.target.value})}/></label></div>{notice&&<p className="manual-note">{notice}</p>}<button className="btn" disabled={busy}>{busy?"...":t({fr:"Créer le produit",ar:"إنشاء المنتج",en:"Create product"})}</button></form></main>
  <aside><form className="panel seller-method-form" onSubmit={addMethod}><h2>{t({fr:"Mes moyens de paiement",ar:"طرق الدفع الخاصة بي",en:"My payment methods"})}</h2><p>{t({fr:"Les acheteurs paieront directement sur ces coordonnées.",ar:"سيدفع المشترون مباشرة إلى هذه البيانات.",en:"Buyers will pay you directly using these details."})}</p><select value={method.method_type} onChange={e=>setMethod({...method,method_type:e.target.value})}><option value="payoneer">Payoneer</option><option value="click">Click</option><option value="bankily">Bankily</option><option value="sedad">Sedad</option><option value="masrvi">Masrvi</option><option value="bank_transfer">Bank transfer</option><option value="other">Other</option></select><input required value={method.label} onChange={e=>setMethod({...method,label:e.target.value})} placeholder="Label"/><input required value={method.account_value} onChange={e=>setMethod({...method,account_value:e.target.value})} placeholder={t({fr:"Compte / numéro / email",ar:"الحساب / الرقم / البريد",en:"Account / number / email"})}/><textarea value={method.instructions} onChange={e=>setMethod({...method,instructions:e.target.value})} placeholder={t({fr:"Instructions facultatives",ar:"تعليمات اختيارية",en:"Optional instructions"})}/><button className="btn btn-ghost">{t({fr:"Ajouter",ar:"إضافة",en:"Add method"})}</button></form><div className="seller-method-list">{methods.map(m=><div key={m.id}><strong>{m.label}</strong><small>{m.method_type} · {m.account_value}</small></div>)}</div><Link className="text-link" href="/marketplace">← Marketplace</Link></aside></div>
  </div></section>
}
