"use client";

import { FormEvent, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { useLanguage } from "../../../components/language-provider";
import { supabase } from "../../../lib/supabase";

export default function ProductPage(){
  const {lang,t}=useLanguage();const params=useParams<{slug:string}>();const [product,setProduct]=useState<any>(null);const [seller,setSeller]=useState<any>(null);const [methods,setMethods]=useState<any[]>([]);const [selected,setSelected]=useState("");const [userId,setUserId]=useState("");const [reference,setReference]=useState("");const [notice,setNotice]=useState("");
  useEffect(()=>{(async()=>{const {data:p}=await supabase.from("marketplace_products").select("*").eq("slug",params.slug).maybeSingle();setProduct(p);if(p){const [{data:s},{data:m},{data:{user}}]=await Promise.all([supabase.from("public_profiles").select("user_id,full_name,username,avatar_url,bio").eq("user_id",p.seller_id).maybeSingle(),supabase.from("marketplace_seller_methods").select("*").eq("seller_id",p.seller_id).eq("is_active",true),supabase.auth.getUser()]);setSeller(s);setMethods(m||[]);setSelected(m?.[0]?.id||"");setUserId(user?.id||"")}})()},[params.slug]);
  async function order(e:FormEvent){e.preventDefault();if(!userId){window.location.href="/connexion";return}if(userId===product.seller_id){setNotice(t({fr:"Vous ne pouvez pas acheter votre propre produit.",ar:"لا يمكنك شراء منتجك.",en:"You cannot buy your own product."}));return}const {error}=await supabase.from("marketplace_orders").insert({product_id:product.id,buyer_id:userId,seller_id:product.seller_id,seller_method_id:selected||null,amount:product.price,currency:product.currency,status:"awaiting_payment",transaction_reference:reference||null});setNotice(error?error.message:t({fr:"Commande créée. Payez directement le vendeur avec les coordonnées affichées.",ar:"تم إنشاء الطلب. ادفع للبائع مباشرة باستخدام البيانات المعروضة.",en:"Order created. Pay the seller directly using the details shown."}))}
  if(!product)return <section className="section page-top"><div className="container">...</div></section>;
  const method=methods.find(m=>m.id===selected);
  return <section className="section page-top product-detail-page"><div className="container"><Link className="text-link" href="/marketplace">← Marketplace</Link><div className="product-detail-grid"><div className="product-detail-cover">{product.image_url?<img src={product.image_url} alt=""/>:<span>V</span>}</div><div><span className="eyebrow">{product.category||"Vydys Marketplace"}</span><h1>{product.title}</h1><p>{product.description}</p><div className="product-seller"><div className="settings-avatar small">{seller?.avatar_url?<img src={seller.avatar_url} alt=""/>:<span>{(seller?.full_name||"V").slice(0,2)}</span>}</div><div><small>{t({fr:"Vendu par",ar:"يباع بواسطة",en:"Sold by"})}</small><strong>{seller?.full_name||seller?.username||"Vydys seller"}</strong></div></div><strong className="product-big-price">{new Intl.NumberFormat(lang==="en"?"en-US":"fr-FR",{style:"currency",currency:product.currency}).format(Number(product.price))}</strong><form className="direct-pay-box" onSubmit={order}><h2>{t({fr:"Payer directement le vendeur",ar:"ادفع مباشرة للبائع",en:"Pay the seller directly"})}</h2><select value={selected} onChange={e=>setSelected(e.target.value)}>{methods.map(m=><option value={m.id} key={m.id}>{m.label} · {m.method_type}</option>)}</select>{method&&<div className="seller-payment-details"><strong>{method.account_value}</strong><p>{method.instructions}</p></div>}<input value={reference} onChange={e=>setReference(e.target.value)} placeholder={t({fr:"Référence de transaction (facultatif)",ar:"مرجع العملية (اختياري)",en:"Transaction reference (optional)"})}/>{notice&&<p className="manual-note">{notice}</p>}<button className="btn" disabled={!methods.length}>{t({fr:"Créer ma commande",ar:"إنشاء الطلب",en:"Create order"})}</button></form></div></div></div></section>
}
